In [1]:
import pandas as pd

# Load the uploaded CSV file
file_path = "train.csv"
df = pd.read_csv(file_path)

# Display the first few rows and basic info
df.head(), df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5847 entries, 0 to 5846
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5847 non-null   int64
 1   Name               5847 non-null   object
 2   Location           5847 non-null   object
 3   Year               5847 non-null   int64
 4   Kilometers_Driven  5847 non-null   int64
 5   Fuel_Type          5847 non-null   object
 6   Transmission       5847 non-null   object
 7   Owner_Type         5847 non-null   object
 8   Mileage            5845 non-null   object
 9   Engine             5811 non-null   object
 10  Power              5811 non-null   object
 11  Seats              5809 non-null   float64
 12  New_Price          815 non-null    object
 13  Price              5847 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 639.6+ KB

(   Unnamed: 0                              Name    Location  Year  \
 0           1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015
 1           2                      Honda Jazz V     Chennai  2011
 2           3                 Maruti Ertiga VDI     Chennai  2012
 3           4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013
 4           6            Nissan Micra Diesel XV      Jaipur  2013

    Kilometers_Driven Fuel_Type Transmission Owner_Type     Mileage   Engine  \
 0              41000    Diesel       Manual      First  19.67 kmpl  1582 CC
 1              46000    Petrol       Manual      First    13 km/kg  1199 CC
 2              87000    Diesel       Manual      First  20.77 kmpl  1248 CC
 3              40670    Diesel    Automatic     Second   15.2 kmpl  1968 CC
 4              86999    Diesel       Manual      First  23.08 kmpl  1461 CC

        Power  Seats  New_Price  Price
 0  126.2 bhp    5.0        NaN  12.50
 1   88.7 bhp    5.0  8.61 Lakh   4.50
 2  88.76 bhp    7.0        NaN   6.00
 3  140.8 bhp    5.0        NaN  17.74
 4   63.1 bhp    5.0        NaN   3.50  ,
 None)

In [2]:
# Check missing values
missing_values = df.isnull().sum()

# Drop 'New_Price' due to too many missing values
df_cleaned = df.drop(columns=['New_Price'])

# Impute missing values for Mileage, Engine, Power with mode (most common format)
for col in ['Mileage', 'Engine', 'Power']:
    df_cleaned[col].fillna(df_cleaned[col].mode()[0], inplace=True)

# Impute missing Seats with median as it's numeric
df_cleaned['Seats'].fillna(df_cleaned['Seats'].median(), inplace=True)

# Verify all missing values are handled
missing_after = df_cleaned.isnull().sum()

missing_values, missing_after

<ipython-input-2-ce2a62954273>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(df_cleaned[col].mode()[0], inplace=True)
<ipython-input-2-ce2a62954273>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned['Seats'].fillna(df_cleaned['Seats'].median(), inplace=True)

(Unnamed: 0              0
 Name                    0
 Location                0
 Year                    0
 Kilometers_Driven       0
 Fuel_Type               0
 Transmission            0
 Owner_Type              0
 Mileage                 2
 Engine                 36
 Power                  36
 Seats                  38
 New_Price            5032
 Price                   0
 dtype: int64,
 Unnamed: 0           0
 Name                 0
 Location             0
 Year                 0
 Kilometers_Driven    0
 Fuel_Type            0
 Transmission         0
 Owner_Type           0
 Mileage              0
 Engine               0
 Power                0
 Seats                0
 Price                0
 dtype: int64)

In [3]:
import re

# Remove non-numeric characters using regular expressions and convert to float
df_cleaned['Mileage'] = df_cleaned['Mileage'].str.extract(r'(\d+\.?\d*)').astype(float)
df_cleaned['Engine'] = df_cleaned['Engine'].str.extract(r'(\d+\.?\d*)').astype(float)
df_cleaned['Power'] = df_cleaned['Power'].str.extract(r'(\d+\.?\d*)').astype(float)

# Confirm changes
df_cleaned[['Mileage', 'Engine', 'Power']].head()

   Mileage  Engine   Power
0    19.67  1582.0  126.20
1    13.00  1199.0   88.70
2    20.77  1248.0   88.76
3    15.20  1968.0  140.80
4    23.08  1461.0   63.10

In [5]:
# Encode categorical features using predefined mappings
fuel_mapping = {'Diesel': 0, 'Petrol': 1, 'Electric': 2}
df['Fuel_Type'] = df['Fuel_Type'].map(fuel_mapping)

transmission_mapping = {'Manual': 0, 'Automatic': 1}
df['Transmission'] = df['Transmission'].map(transmission_mapping)

# Display the first few rows of the DataFrame
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [6]:

from datetime import datetime

current_year = datetime.now().year

In [22]:
# Ensure all values are treated as strings before cleaning
df['Mileage'] = df['Mileage'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)
df['Power'] = df['Power'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# Convert Seats to float (in case it's not already)
df['Seats'] = df['Seats'].astype(float)

# Compute derived metrics
df['Power_per_Liter'] = (df['Power'] / df['Mileage']).round(2)
df['Mileage_per_Seat'] = (df['Mileage'] / df['Seats']).round(2)

# Calculate the age of the car
df['Age_of_Car'] = current_year - df['Year']

# Display updated DataFrame
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582 CC,126.20,5.0,NaN,12.50,10,6.42,3.93
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199 CC,88.70,5.0,8.61 Lakh,4.50,14,6.82,2.60
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248 CC,88.76,7.0,NaN,6.00,13,4.27,2.97
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968 CC,140.80,5.0,NaN,17.74,12,9.26,3.04
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461 CC,63.10,5.0,NaN,3.50,12,2.73,4.62

In [23]:
required_columns = ['Name', 'Mileage', 'Engine', 'Seats']
df_selected = df[required_columns]
df_selected.head()

                               Name  Mileage   Engine  Seats
0  Hyundai Creta 1.6 CRDi SX Option    19.67  1582 CC    5.0
1                      Honda Jazz V    13.00  1199 CC    5.0
2                 Maruti Ertiga VDI    20.77  1248 CC    7.0
3   Audi A4 New 2.0 TDI Multitronic    15.20  1968 CC    5.0
4            Nissan Micra Diesel XV    23.08  1461 CC    5.0

In [26]:
# Clean the 'Engine' column by extracting only the numeric part
df['Engine'] = df['Engine'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# Clean the 'Mileage' column similarly if not already done
df['Mileage'] = df['Mileage'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# Filter rows based on Mileage > 20 and Engine < 1500
filtered_df = df[(df['Mileage'] > 20) & (df['Engine'] < 1500)]

# Preview the filtered DataFrame
filtered_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,NaN,6.00,13,4.27,2.97
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,NaN,3.50,12,2.73,4.62
7,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,0,0,Second,22.30,1248.0,74.00,5.0,NaN,1.95,13,3.32,4.46
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,1,0,First,21.56,1462.0,103.25,5.0,10.65 Lakh,9.95,7,4.79,4.31
10,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,0,0,First,25.20,1248.0,74.00,5.0,NaN,5.60,10,2.94,5.04

In [27]:
renamed_df = df.rename(columns={'Power_per_Liter': 'Power_per_Fuel'})
renamed_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age_of_Car,Power_per_Fuel,Mileage_per_Seat
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,NaN,12.50,10,6.42,3.93
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,8.61 Lakh,4.50,14,6.82,2.60
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,NaN,6.00,13,4.27,2.97
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,NaN,17.74,12,9.26,3.04
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,NaN,3.50,12,2.73,4.62

In [28]:
sorted_df = df.sort_values(by=['Age_of_Car', 'Mileage'], ascending=[True, False])
sorted_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
4198,4328,Maruti Swift DDiS VDI,Coimbatore,2019,41075,0,0,First,28.40,1248.0,74.0,5.0,NaN,8.40,6,2.61,5.68
984,1018,Maruti Swift Dzire VDI Optional,Kochi,2019,18592,0,0,First,26.59,1248.0,74.0,5.0,NaN,8.51,6,2.78,5.32
4267,4399,Maruti Swift Dzire AMT ZDI,Chennai,2019,65000,0,1,First,26.59,1248.0,74.0,5.0,NaN,6.75,6,2.78,5.32
5405,5560,Renault KWID RXT Optional,Kochi,2019,6568,1,0,First,25.17,799.0,53.3,5.0,4.78 Lakh,5.09,6,2.12,5.03
5628,5789,Renault KWID RXL,Kochi,2019,7858,1,0,First,25.17,799.0,53.3,5.0,4.04 Lakh,3.80,6,2.12,5.03

In [29]:
df['Avg_Mileage_Location'] = df.groupby('Location')['Mileage'].transform('mean')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat,Avg_Mileage_Location
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,NaN,12.50,10,6.42,3.93,17.886576
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,8.61 Lakh,4.50,14,6.82,2.60,18.236674
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,NaN,6.00,13,4.27,2.97,18.236674
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,NaN,17.74,12,9.26,3.04,17.844200
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,NaN,3.50,12,2.73,4.62,19.189777

In [30]:
grouped_df = df.groupby('Fuel_Type').agg({'Mileage': 'mean'}).sort_values(by='Mileage', ascending=False)
grouped_df.head()

             Mileage
Fuel_Type
0          18.652661
1          17.576509
2                NaN